# https://www.mkdocs.org/user-guide/configuration/
site_name: BrightWebApp
repo_url: https://github.com/brightway-lca/brightwebapp
copyright: © Paul Scherrer Institute (PSI) and Contributors | Code under MIT License
nav: 
  - Home: 'index.md'
  - About: 'about.md'
  - FAQ: 'faq.md'
  - Theory:
    - Scopes: 'theory/scopes.md'
  - API (Python):
    - Traversal: 'api/traversal.md'
    - Modifications: 'api/modifications.md'
    - Brightway: 'api/brightway.md'
    - Tests: 'api/tests.md'
  - API (FastAPI):
    - Endpoints: 'api/endpoints.md'
  - Web Application:
    - Development: 'webapp.md'
  - Changelog: 'changelog.md'
theme: # https://www.mkdocs.org/user-guide/choosing-your-theme/#readthedocs
  name: material
  #custom_dir: docs/_overrides
  logo: _logos/brightwebapp_logo.svg
  favicon: _logos/brightwebapp_logo.svg
  highlightjs: true
  navigation_depth: 4
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.footnote.tooltips
    - content.code.select
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings: # https://mkdocstrings.github.io/python/usage/
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_toc_entry: True
            show_root_heading: true
            heading_level: 2
            show_source: true
            filters: []
  - markdown-exec
  - autorefs
  - include-markdown
  - swagger-ui-tag
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - _javascripts/katex.js
  # https://cdnjs.com/libraries/KaTeX
  # unpkg is incredibly slow (17s to load the css file)
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
extra_css:
  # https://cdnjs.com/libraries/KaTeX
  # unpkg is incredibly slow (17s to load the css file)
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.43.0/swagger-ui.css
  - _css/extra.css

watch:
  - src/brightwebapp
  - api

extra:
  generator: false