# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
name: panel
channels:
  - conda-forge
  - nodefaults
dependencies:
  # core functionality
  - python=3.13
  # panel
  - panel=1.6.1 # https://anaconda.org/conda-forge/panel/files
  # data science
  - jupyterlab
  - scipy  
  - pandas
  - numpy
  # plotting
  - matplotlib
  - plotly